#pragma once

#include <QLoggingCategory>

Q_DECLARE_LOGGING_CATEGORY(sunplayerLogApplication)
Q_DECLARE_LOGGING_CATEGORY(sunplayerLogMediaIo)
Q_DECLARE_LOGGING_CATEGORY(sunplayerLogMediaDecode)
Q_DECLARE_LOGGING_CATEGORY(sunplayerLogPlayback)
Q_DECLARE_LOGGING_CATEGORY(sunplayerLogGraphics)
Q_DECLARE_LOGGING_CATEGORY(sunplayerLogVideo)
Q_DECLARE_LOGGING_CATEGORY(sunplayerLogPresentation)
Q_DECLARE_LOGGING_CATEGORY(sunplayerLogPlatform)
