name: Release

on:
  workflow_dispatch:
    inputs:
      bump:
        description: Version bump
        required: true
        type: choice
        options:
          - patch
          - minor
          - major

permissions:
  contents: read

jobs:
  release:
    permissions:
      actions: read
      contents: write
    uses: ./.github/workflows/ci.yml
    with:
      release: true
      bump: ${{ inputs.bump }}
